### ISSUE TITLE
reshape and reshaped_view syntax

### ISSUE THREAD

**Issue by jasonkaye** [TRIQS/nda#32]
When calling reshape or reshaped_view, the syntax

reshape(A,i,j,k)

would be preferable to the current one, which requires you to pass in a vector specifying the shape. Also,

A.reshape(i,j,k)

would be fine as well.

**Comment by Wentzell** [comment]
Dear @jasonkaye,

Thank you for the suggestion.

The free reshape function has been extended to allow for the first syntax you suggested.
