### ISSUE TITLE
Bug report: Use of nda with openmp 

### ISSUE THREAD

**Issue by mmorale3** [TRIQS/nda#37]
### Description

nda can not be used in combination with openmp, even when use of nda is strictly avoided inside parallel regions.
The specific line that prevents it is in c++/nda/mem/policies.hpp,

#ifdef _OPENMP
    static_assert(false and !std::is_void_v<Allocator>, "Custom Allocators are not available in OpenMP");
#endif

**Comment by Wentzell** [comment]
This was fixed on unstable
