### ISSUE TITLE
nda::zeros for fortran layout

### ISSUE THREAD

**Issue by jasonkaye** [TRIQS/nda#42]
`nda::zeros` does not work for Fortran layout arrays. I'd like to be able to write

`auto b = nda::zeros<double, F_layout>(m,n,p);`

and get an array of zeros in Fortran layout.

**Comment by Wentzell** [comment]
Dear @jasonkaye,

For each array type you can use the static member function `zeros`

```c++
auto ac = nda::array<double, 3>::zeros(m,n,p);
auto af = nda::array<double, 3, F_layout>::zeros(m,n,p);
```

The free function `nda::zeros` is intended for the default array case and does at this point not allow for customizations of memory layout, algebra and such.

**Comment by jasonkaye** [comment]
Excellent, thanks Nils.
