### ISSUE TITLE
Lazy transpose for rank==2 arrays

### ISSUE THREAD

**Issue by Wentzell** [TRIQS/nda#9]
Currently the transpose function can only operate on `basic_array` and `basic_array_view`.
It would be nice to be able to write expressions like

```c++
arr + tranpose(conj(arr))
```

This would require an overload of transpose that takes a general argument fulfilling the array concept.
The result of this overload would be a lazy object instead f an `basic_array_view`.

**Comment by parcollet** [comment]
Yes. d=2 only ?

**Comment by Wentzell** [comment]
This is now possible on the unstable branch
